# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MDIyN2UyN2Q2NTI0ODA0MzhiZmU1M2U0OWFjNzkwNWYzMGY0NjhiMTY4ZjBjN2E3OGQzZTI0NjdlNTExYmIwNzcyMzQ2YjUwYmZiY2FlZjAwZjRjYzZhNGNjZjI1YzA5YmQ3OTI0YTYxY2UzNzkzZTVmNzdjMjNhOTMwMjBiYWM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
