# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OGM0NTZlOGE1MDg3MTNiZDYzMTdjZjQ2MGYyMmU0ZWZiNDQ2YzMwMzk5MTVjOWJhYzkyMWU3YWI5Yzg2YmRmYjc1ODQ0N2U3ZGYyOGYzNjc4Mzc3M2VmMmY2NWI1ZWZlYzNlYjRkZGZlYjFkZmY0YzQ1MmRlMTExNjM2ZjZiNjc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
